using UnityEngine;
using UnityEngine.InputSystem;


public class PLayerMovement : MonoBehaviour
{
    // FEATURE LIST
    // 1. Use arrow key for movement 
    // 2. need a variable for speed
    // 3. We need to store the direction of our character
    // 4. need a variable for running
    // 5. speical movement example: rolling or dashing
    // 6. Mantling
    // 7. If we can climb or not

    private float moveSpeed = 5f;
    private Rigidbody2D rb;
    private Vector2 moveInput;
    private Animator animator;


    

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();
    }

    // Update is called once per frame
    void Update()
    {
        rb.linearVelocity = moveInput * moveSpeed;
    }
    public void Move(InputAction.CallbackContext context)
    {
        animator.SetBool("isWalking", true);
        if (context.canceled)
        {
            animator.SetBool("isWalking", false);
            animator.SetFloat("LastinputX", moveInput.x);
            animator.SetFloat("LastInputY", moveInput.y);
        }
              moveInput = context.ReadValue<Vector2>();

        animator.SetFloat("InputX", moveInput.x);
        animator.SetFloat("InputY", moveInput.y);
    }

}
